name: Build and Deploy to k8s

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 985883769551.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: rigettidemo
  IMAGE_TAG: build-${{ github.run_id }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ env.IMAGE_TAG }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image with multiple tags
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
                     -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }} .

    - name: Push both tags
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}

  deploy:
    name: Update values repo
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Clone values repo
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        git clone https://kollzey539:${{ secrets.VALUES_REPO_PAT }}@github.com/kollzey539/values.git ~/values_repo
        cd ~/values_repo

        # Update the image tag in hash-store/values.yaml
        sed -i 's/tag: .*/tag: build-${{ github.run_id }}/' hash-store/values.yaml

        git add hash-store/values.yaml
        git commit -m "Update hash-store image tag to build-${{ github.run_id }}"
        git push origin main
        sleep 120
